services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   # pull_policy: always
  #   # tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  #   extra_hosts:
  #     - host.docker.internal:host-gateway

  open-webui:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    # depends_on:
    #   - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - CUSTOM_NAME="Telkomsel AI Labs"
      - PYTHONHTTPSVERIFY=0
      # - OLLAMA_BASE_URL=http://ollama:11434
      - AIOHTTP_CLIENT_SESSION_SSL=False
      - AIOHTTP_CLIENT_SESSION_TOOL_SERVER_SSL=False
      - ENABLE_API_KEYS_ENDPOINT_RESTRICTIONS=False
      - ENABLE_WEB_LOADER_SSL_VERIFICATION=False
      - ENABLE_API_KEYS=True
      - VECTOR_DB=qdrant
      - QDRANT_URI=http:localhost:6333
      # - CORS_ALLOW_ORIGIN="*"
      # - ENABLE_LDAP=False
      - API_KEYS_ALLOWED_ENDPOINTS=True
      # - CORS_ALLOW_ORIGIN="http://localhost"
      # - ENABLE_WEBSOCKET_SUPPORT=True
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  # ollama: {}
  open-webui: {}